mysite/eticket/urls.py
from django.urls import path, re_path


from . import views
app_name = 'eticket'
urlpatterns = [
    path("", views.home, name="home"),
    path("venue/", views.venue, name="venue"),
    path("event/", views.hostEvent, name="event"),
    path("ticket/", views.buyTickets, name="ticket"),
    path("get_ticket_price/<str:event_id>/", views.getTicketPrice, name="getTicketPrice"),
    path("get_balance/", views.getBalance, name="getBalance"),
]   

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("users.urls")),
    path("eticket/", include("eticket.urls", "eticket")),
    path('admin/', admin.site.urls),
]

mysite/users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path("", views.loginPage, name="loginPage"),
    path("register/", views.register, name="register"),
    path("logout/", views.logoutPage, name="logoutPage"),
]

mysite/eticket/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
class Venue(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    capacity = models.PositiveIntegerField(default=0)

class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    eventName = models.CharField(max_length=50, default="")
    host = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE, null=True)
    ticketPrice = models.DecimalField(max_digits=10, decimal_places=2, default=50)
    ticketQuantity = models.PositiveIntegerField(default=0)

class Ticket(models.Model):
    id = models.IntegerField(primary_key=True)
    row = models.SmallIntegerField(default=0)
    seatNum = models.SmallIntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    ticketHolder = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return self.user.username

mysite/eticket/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from .models import Venue, Event, Ticket
from users.models import Account
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required
def home(request):
    context = {}
    return render(request, "eticket/home.html", context)

@login_required
def venue(request):
    venues = Venue.objects.all()
    if request.method == 'POST':
        venue_name = request.POST.get('name')
        location = request.POST.get('location')
        capacity = request.POST.get('capacity')
        Venue.objects.create(
            name=venue_name, 
            location=location, 
            capacity=capacity, 
            owner=request.user
        )
        return redirect('eticket:venue')
    context = {'venues':venues}
    return render(request, "eticket/venue.html", context)


@login_required
def hostEvent(request):
    events = Event.objects.all()
    venues = Venue.objects.all()
    if request.method == 'POST':
        event_name = request.POST.get('eventName')
        venue_id = request.POST.get('venue')
        venue = Venue.objects.get(pk=venue_id)
        price = request.POST.get('ticketPrice')
        Event.objects.create(
            eventName=event_name,
            host=request.user,
            venue=venue,
            ticketPrice = price,
            ticketQuantity = venue.capacity,
        )
        return redirect('eticket:event')
    context = {'events':events, 'venues':venues}
    return render(request, "eticket/hostEvent.html", context)

@login_required
def buyTickets(request):
    tickets = Ticket.objects.filter(ticketHolder=request.user)
    account = Account.objects.get(user=request.user)
    events = Event.objects.all()
    if request.method == 'POST':
        row = int(request.POST.get('row'))
        seat_num = int(request.POST.get('seatNum'))
        event_id = request.POST.get('event')
        event = Event.objects.get(pk=event_id)
        quantity = request.POST.get('quantity') 
        event.ticketQuantity -= int(quantity)
        event.save()
        price = int(quantity) * event.ticketPrice
        account.balance -= price
        account.save() 
        for i in range(int(quantity)):
            Ticket.objects.create(
                row=row, 
                seatNum = seat_num,
                event=event,
                ticketHolder=request.user
            )
        return redirect('eticket:ticket')
    context = {'tickets':tickets, 'events':events}
    return render(request, "eticket/buyTicket.html", context)

@login_required
def getTicketPrice(request, event_id):
    event = Event.objects.get(pk=event_id)
    quantity = event.ticketPrice
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse(quantity, safe=False)

@login_required
def getBalance(request):
    account = Account.objects.get(user=request.user)
    balance = account.balance
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse(balance, safe=False)

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Account
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.

def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
            auth = authenticate(request, username=username, password=password)
            if auth is not None:
                login(request, user)
                return redirect('eticket:home')
            else:
                messages.error(request, 'The Password is Incorrect')
        except Exception as e:
            messages.error(request, "The username does Not Exist")

    context = {}
    return render(request, "users/login.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Account.objects.create(
                user = user,
                balance = 0
            )
            return redirect('users:loginPage')
        else:
            messages.error(request, 'Could Not Register account')

    context = {'form':form}
    return render(request, "users/registration.html", context)

def logoutPage(request):
    logout(request)
    return redirect('users:loginPage') 

mysite/eticket/templates/eticket/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}ETicket{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
        {% block extra_css %}

        {% endblock %}
    </head>
    <body>
        <header>
            <nav class="navbar">
                <h2 class="logo"><a href="{% url 'eticket:home' %}">ETicket</a></h2>
                <ul class="all-links">
                    <li id="username"><span>Hello,  {{request.user}}</span></li>
                    <li><span id="balance">Balance:  $0</span></li>
                    <li><a href="">Settings</a></li>
                    <li><a href="{% url 'users:logoutPage' %}">Logout</a></li>
                    <li id="bell-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4 19v-2h2v-7q0-2.075 1.25-3.688T10.5 4.2v-.7q0-.625.438-1.063T12 2q.625 0 1.063.438T13.5 3.5v.7q2 .5 3.25 2.113T18 10v7h2v2H4Zm8 3q-.825 0-1.413-.588T10 20h4q0 .825-.588 1.413T12 22Z"/></svg>
                    </li>                
                </ul>
            </nav>
        </header>
        <div id="contentwrapper">
            <div id="content">
                {% block content %}
        
                {% endblock %}
            </div>
        </div>
        <script>
            const csrfToken = "{{ csrf_token }}";
        </script>
        <script src="{% static 'js/base.js' %}"></script>
    </body>
</html>

mysite/eticket/templates/eticket/buyTicket.html
{% extends 'eticket/base.html' %}
{% load static %}

{% block title %}ETicket{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/venue.css' %}">
{% endblock %}

{% block content %}
<div id="addbtn"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12"><path fill="white" d="M6.5 1.75a.75.75 0 0 0-1.5 0V5H1.75a.75.75 0 0 0 0 1.5H5v3.25a.75.75 0 0 0 1.5 0V6.5h3.25a.75.75 0 0 0 0-1.5H6.5V1.75Z"/></svg></div>
<div id="hidden-wrapper">
    <div class="form-wrapper">
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <label for="name" class="textarea-label">Ticket</label>

            <select name="event" id="event" placeholder="Select Event">
                {% for event in events %}
                    {% if event.ticketQuantity > 0 %}
                    <option value="{{ event.id }}">{{ event.eventName }}</option>
                    {% endif %}
                {% endfor %}
            </select>
                
            <input
                type="number"
                name="row"
                id="row"
                placeholder="Row Number"
                class="textarea-input"
            />
            <input
                type="number"
                name="seatNum"
                id="seatNum"
                placeholder="Seat Number"
                class="textarea-input"
            />

            <input
                type="number"
                name="quantity"
                id="quantity"
                placeholder="Ticket Quantity"
                class="textarea-input"
            />
            <div class="total">
                <span>TOTAL: </span> <span id="price">$0</span>
            </div>
            <button class="btn">
                Buy Tickets
            </button>
        </form>
    </div>
</div>
<div class="venue-wrapper" id="venue-wrapper">
    {% for ticket in tickets %}
        <div class="venue">
            <span>Event name: {{ticket.event.eventName}}</span>
            <span>Ticket Holder: {{ticket.ticketHolder.username}}</span>
            <span>Venue: {{ticket.event.venue.name}}, &nbsp;{{ticket.event.venue.location}}</span>
            <div>
                <span>Seat #: {{ticket.seatNum}}</span> 
                <span>&nbsp;&nbsp;&nbsp;Row #: {{ticket.row}}</span> 
            </div>
        </div>
    {% endfor %}
</div>
<script src="{% static 'js/buyTicket.js' %}"></script>
{% endblock %}

mysite/eticket/templates/eticket/home.html
{% extends 'eticket/base.html' %}
{% load static %}

{% block title %}ETicket{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div class="center-wrapper">
        <h1 class="title">Event Management Done Different</h1>
        <div class="buttons">
            <a href="{% url 'eticket:ticket' %}">Buy Tickets</a>
            <a href="{% url 'eticket:event' %}">Host Event</a>
            <a href="{% url 'eticket:venue' %}">Add Venue</a>
        </div>
    </div>
    <div id="background"></div>
{% endblock %}

mysite/eticket/templates/eticket/hostEvent.html
{% extends 'eticket/base.html' %}
{% load static %}

{% block title %}ETicket{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/venue.css' %}">
{% endblock %}

{% block content %}
<div id="addbtn"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12"><path fill="white" d="M6.5 1.75a.75.75 0 0 0-1.5 0V5H1.75a.75.75 0 0 0 0 1.5H5v3.25a.75.75 0 0 0 1.5 0V6.5h3.25a.75.75 0 0 0 0-1.5H6.5V1.75Z"/></svg></div>
<div id="hidden-wrapper">
    <div class="form-wrapper">
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <label for="eventName" class="textarea-label">Host an Event</label>
            <select name="venue" id="venue">
                {% for venue in venues %}
                    <option value="{{ venue.id }}">{{ venue.name }}</option>
                {% endfor %}
            </select>
            <input
                type="text"
                name="eventName"
                id="eventName"
                placeholder="Name of Event"
                class="textarea-input"
            />
            <input
                type="text"
                name="ticketPrice"
                id="ticketPrice"
                placeholder="Price of Ticket"
                class="textarea-input"
            />
            <button class="btn">
                Add Event
            </button>
        </form>
    </div>
</div>
<div class="venue-wrapper" id="venue-wrapper">
    {% for event in events %}
        <div class="venue">
            <span>Event name: {{event.eventName}}</span>
            <span>Venue: {{event.venue.name}}, &nbsp;{{event.venue.location}}</span>
            <span>Host: {{event.host}}</span>
            <span>Ticket Price: ${{event.ticketPrice}}</span>
            <span>Tickets Available: {{event.ticketQuantity}}</span>
        </div>
    {% endfor %}
</div>
<script src="{% static 'js/hostEvent.js' %}"></script>
{% endblock %}

mysite/eticket/templates/eticket/venue.html
{% extends 'eticket/base.html' %}
{% load static %}

{% block title %}ETicket{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/venue.css' %}">
{% endblock %}

{% block content %}
<div id="addbtn"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12"><path fill="white" d="M6.5 1.75a.75.75 0 0 0-1.5 0V5H1.75a.75.75 0 0 0 0 1.5H5v3.25a.75.75 0 0 0 1.5 0V6.5h3.25a.75.75 0 0 0 0-1.5H6.5V1.75Z"/></svg></div>
<div id="hidden-wrapper">
    <div class="form-wrapper">
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <label for="name" class="textarea-label"> Venue</label>
            <input
                type="text"
                name="name"
                id="name"
                placeholder="Venue name"
                class="textarea-input"
            />
            <input
                type="text"
                name="location"
                id="location"
                placeholder="Address"
                class="textarea-input"
            />
            <div class="form-group">
                <label for="capacity">Capacity:</label>
                <input type="number" id="capacity" name="capacity" min="1" value="0" />
            </div>
    
            <button class="btn">
                Add Venue
            </button>
        </form>
    </div>
</div>
<div class="venue-wrapper" id="venue-wrapper">
    {% for venue in venues %}
        <div class="venue">
            <span>Venue name: {{venue.name}}</span>
            <span>Owner: {{venue.owner}}</span>
            <span>Address: {{venue.location}}</span>
            <span>Capacity: {{venue.capacity}}</span>
        </div>
    {% endfor %}
</div>
<script src="{% static 'js/venue.js' %}"></script>
{% endblock %}

mysite/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body>
  <h1 class="title">ETicket <br> Event Management</h1>
  <div class="login">
      <h1>Login</h1>
      <form method="POST" action="">
          {% csrf_token %}
        <div >
          <input class="input-box" type="text" name="username" id="username" placeholder="Username or Email" value="">
        </div>
        <div>
          <input class="input-box" type="password" name="password" id="password" placeholder="Password" value="" >
        </div>
        <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>
        <div class="text">
          <h3>Need an account? <a href="{% url 'users:register' %}">Sign up now</a></h3>
        </div>
      </form>
  </div>
  <div id="error-message">
    {% if messages %}

            {% for message in messages %}
                {{message}}
            {% endfor %}
    {% endif %}
  </div>
</body>
</html>

mysite/users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration </title> 
    {% load static %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
   </head>
<body>
  <div class="login">
    <h1>Registration</h1>
    <form method="POST" action="">
        {% csrf_token %}
      <div>
        <input class="input-box" type="username" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}" placeholder="username" >
      </div>
      <div>
        <input class="input-box" type="password" name="{{ form.password1.name }}" id="{{ form.password1.id_for_label }}" placeholder="Password" >
      </div>
      <div >
        <input class="input-box" type="password" name="{{ form.password2.name }}" id="{{ form.password2.id_for_label }}" placeholder="Confirm Your Password" >
      </div>
      <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>
      <div class="text">
        <h3>Already have an account? <a href="{% url 'users:loginPage' %}">Login now</a></h3>
      </div>
    </form>
  </div>
  <div id="error-message">
    {% if messages %}

            {% for message in messages %}
                {{message}}
            {% endfor %}
    {% endif %}
  </div>
</body>
</html>